config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  resources :users do
    resources :widgets

    collection do
      post :sign_in
      delete :sign_out
    end
  end

  root to: "home#index"
end

app/views/shared/modals/_login.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Sign In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= simple_form_for(User.new, method: :post, url: sessions_path) do |f| %>
        <div class="modal-body">
          <%= flash[:error]%>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :email %>
            <%= f.input :password %>
          </div>

          <div class="form-actions">

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, 'Sign in', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/modals/_sign_in.html.erb
<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="signInModalLabel">Sign In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= simple_form_for(:user, method: :post, url: sign_in_users_path) do |f| %>
        <div class="modal-body">
          <div class="form-inputs">
            <%= f.input :email %>
            <%= f.input :password %>
          </div>

          <div class="form-actions">

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, 'Sign in', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/modals/_sign_up.html.erb
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="signUpModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="signUpModalLabel">Sign In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= simple_form_for(:user, method: :post, url: users_path) do |f| %>
        <div class="modal-body">
          <div class="form-inputs">
            <%= f.input :first_name %>
            <%= f.input :last_name %>
            <%= f.input :date_of_birth, as: :string, input_html: { type: :date } %>
            <%= f.input :email %>
            <%= f.input :password %>
            <%= f.input :image_url %>
          </div>

          <div class="form-actions">

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>