config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  resources :users do
    resources :widgets

    collection do
      post :sign_in
      delete :sign_out
    end
  end

  root to: "home#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Showoff</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if current_user %>
        <li class="nav-item <%= 'active' if current_page?(widgets_path) %>">
          <%= link_to "My Widgets", widgets_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

    <%= simple_form_for :search, url: controller_name == 'widgets' ? widgets_path : root_path, method: "GET", html: { class: 'form-inline my-2 my-lg-0 ml-3 f-1' } do |f| %>
      <%= f.input :widget_term, label: false, input_html: { value: @search_term, class: 'form-control mr-sm-2' }, placeholder: 'Search widgets' %>
      <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>

    <% if current_user %>
      <div class="nav-link">
        <span class="text-muted">Hello, <%= current_user&.name %>!</span>
      </div>

      <%= link_to "Sign out", sign_out_users_path, method: :delete, class: "btn btn-outline-danger ml-2" %>
    <% else %>
      <button type="button" class="btn btn-success mr-2" data-toggle="modal" data-target="#signUpModal">
        Sign Up
      </button>

      <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#signInModal">
        Sign In
      </button>
    <% end %>
  </div>
</nav>