config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  resources :users do
    resources :widgets

    collection do
      post :sign_in
      delete :sign_out
    end
  end

  root to: "home#index"
end

app/models/widget.rb
class Widget
  include ShowoffApiResource

  module Kinds
    VISIBLE = 'visible'.freeze
    HIDDEN = 'hidden'.freeze
  end

  KINDS_AVAILABLE = [Kinds::VISIBLE, Kinds::HIDDEN]

  attr_reader :user

  attribute :id, :integer
  attribute :name, :string
  attribute :description, :string
  attribute :kind, :string
  attribute :owner, :boolean

  validates :id, presence: true, on: :update
  validates :kind, inclusion: { in: KINDS_AVAILABLE }
  validates :owner, inclusion: { in: [true, false] }, allow_blank: true
  validates :name, :description, presence: true

  def visible?
    kind == Kinds::VISIBLE
  end

  def hidden?
    kind == Kinds::HIDDEN
  end

  def user=(user)
    @user = user.is_a?(User) ? user : User.new(user)
  end

  def self.only_visible(term = nil)
    all(
      path: "#{plural_name}/visible",
      params: { term: term },
      include_query_credentials: true,
      # skip_access_token: true
    )
  end

  def self.by_user_id(id, term = nil)
    all(
      path: "users/#{id}/#{plural_name}",
      params: { term: term },
      include_query_credentials: true,
    )
  end

  def self.own_widgets(term = nil)
    by_user_id('me', term)
  end

  def create!
    create(
      widget: {
        name: name,
        description: description,
        kind: kind
      }
    )
  end

  def update!
    update(
      id,
      widget: {
        name: name,
        description: description,
        kind: kind
      }
    )
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @search_term = search_params[:widget_term] if params[:search]
    @widgets = Widget.by_user_id(user_id, @search_term)
  end

  # TODO: add validations and rescue errors
  def destroy
    Widget.destroy!(params[:id])

    redirect_to widgets_path
  end

  def edit
    @widget = Widget.find(params[:id])
  end

  def update
    @widget = Widget.new(
      widget_params.merge(id: params[:id])
    )

    if @widget.update!
      redirect_to widgets_path
    else
      render 'edit'
    end
  end

  def new
    @widget = Widget.new
  end

  def create
    @widget = Widget.new(widget_params)

    if @widget.create!
      redirect_to widgets_path
    else
      render 'new'
    end
  end

  private

    def user_id
      params[:user_id].presence || 'me'
    end

    def search_params
      params.require(:search).permit(
        :widget_term
      )
    end

    def widget_params
      params.require(:widget).permit(
        :name,
        :description,
        :kind
      )
    end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.erb
<%= simple_form_for widget do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :kind, collection: Widget::KINDS_AVAILABLE, default: Widget::Kinds::VISIBLE %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/widgets/_list.html.erb
<div class="container mt-5">
  <div class="row">
    <% if @widgets.empty? %>
      <p>No entries found.</p>
    <% end %>
    <% @widgets.each do |widget| %>
      <div class="col-md-3">
        <div class="card mb-3 box-shadow">
          <img class="card-img-top" alt="Thumbnail [100%x225]" src="<%= widget.user.images.small_url %>" data-holder-rendered="true">
          <div class="card-body">
            <h5 class="card-title">
              <%= widget.name %>
            </h5>

            <p class="card-text"><%= widget.description %></p>

            <% if widget.hidden? %>
              <span class="badge badge-secondary">hidden</span>
            <% end %>
            <% if widget.owner %>
              <span class="badge badge-success">owner</span>
            <% end %>

            <div class="mt-3 d-flex justify-content-between align-items-center">
              <% if current_user == widget.user %>
                <div class="btn-group">
                  <%= link_to "Edit", edit_widget_path(widget.id), class: "btn btn-sm btn-outline-secondary" %>
                  <%= link_to "Remove", widget_path(widget.id), method: :delete, class: "btn btn-sm btn-outline-danger" %>
                </div>
              <% end %>
              <small class="text-muted" title="author"><%= current_user ? link_to(widget.user.name, user_widgets_path(widget.user.id)) : widget.user.name %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/widgets/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-8">
      <h4 class="mb-3">Edit widget</h4>

      <%= render partial: 'form', locals: { widget: @widget } %>
    </div>
  </div>
</div>

app/views/widgets/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-8">
      <%= link_to "Create a new widget", new_widget_path %>
    </div>
  </div>
</div>

<%= render "widgets/list" %>

app/views/widgets/new.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-8">
      <h4 class="mb-3">New widget</h4>

      <%= render partial: 'form', locals: { widget: @widget } %>
    </div>
  </div>
</div>